name: Run Python Tests
on: 
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Install Pyhton 3
        uses: action/setup-python@v1
        with:
          python-version:3.9
      - name: Install Dependencies
        run:
          python -m pip install --updrage pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
